### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by TheCoordinator** [417-72KI/danger-swiftlint#15]
Thanks for adding this. The Danger official docker on Github doesn't work for SwiftLint. 

See issue here https://github.com/danger/swift/issues/339

Are you planning to keep this maintained?

**Comment by 417-72KI** [comment]
I have created this Docker image and action for the same reason 😄

I'm also using it in my own project, and will keep it as long as the development continues.

**Comment by TheCoordinator** [comment]
@417-72KI Awesome, thanks! Do you think if there's an easy way we can add executables to the docker image instead of building both danger and swiftlint on machine every time? Believe that's what the original docker instance on danger is supposed to do.

**Comment by TheCoordinator** [comment]
If we can add executables, that would certainly speed things up quite a lot.
