### ISSUE TITLE
Looks like lint is still 0.49.1

### ISSUE THREAD

**Issue by khoogheem** [417-72KI/danger-swiftlint#41]
when I use the image in Bitbucket `image: 41772ki/danger-swiftlint`

I get:
```
+ swift --version
Swift version 5.7 (swift-5.7-RELEASE)
Target: x86_64-unknown-linux-gnu
```

```
+ danger-swift --version
3.14.0
```

```
+ swiftlint --version
0.49.1
```

doesn't seem to pull the most current SwiftLint `0.50.3` or danger `3.15`

**Comment by 417-72KI** [comment]
There are few mistakes on deploy workflow, and fixed now 🙇 
You can use the latest SwiftLint with 5.7 image!
